### ISSUE TITLE
Unable to complete the final step. 

### ISSUE THREAD

**Issue by kishor578** [renato-farias/openstack-instances-monitoring#2]
[2016-08-12 09:18:14 +0000] [25020] [INFO] Starting gunicorn 19.3.0
[2016-08-12 09:18:14 +0000] [25020] [INFO] Listening at: http://0.0.0.0:8000 (25020)
[2016-08-12 09:18:14 +0000] [25020] [INFO] Using worker: sync
[2016-08-12 09:18:14 +0000] [25035] [INFO] Booting worker with pid: 25035
[2016-08-12 09:18:14 +0000] [25035] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/root/.virtualenvs/monitoring/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/root/.virtualenvs/monitoring/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/root/.virtualenvs/monitoring/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.virtualenvs/monitoring/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/root/.virtualenvs/monitoring/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.virtualenvs/monitoring/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    **import**(module)
ImportError: No module named app
Traceback (most recent call last):
  File "/root/.virtualenvs/monitoring/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/root/.virtualenvs/monitoring/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/root/.virtualenvs/monitoring/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.virtualenvs/monitoring/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/root/.virtualenvs/monitoring/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.virtualenvs/monitoring/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    **import**(module)
ImportError: No module named app
[2016-08-12 09:18:14 +0000] [25035] [INFO] Worker exiting (pid: 25035)
Traceback (most recent call last):
  File "/root/.virtualenvs/monitoring/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/root/.virtualenvs/monitoring/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/root/.virtualenvs/monitoring/lib/python2.7/site-packages/gunicorn/app/base.py", line 189, in run
    super(Application, self).run()
  File "/root/.virtualenvs/monitoring/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/root/.virtualenvs/monitoring/lib/python2.7/site-packages/gunicorn/arbiter.py", line 174, in run
    self.manage_workers()
  File "/root/.virtualenvs/monitoring/lib/python2.7/site-packages/gunicorn/arbiter.py", line 477, in manage_workers
    self.spawn_workers()
  File "/root/.virtualenvs/monitoring/lib/python2.7/site-packages/gunicorn/arbiter.py", line 541, in spawn_workers
    time.sleep(0.1 \* random.random())
  File "/root/.virtualenvs/monitoring/lib/python2.7/site-packages/gunicorn/arbiter.py", line 214, in handle_chld
    self.reap_workers()
  File "/root/.virtualenvs/monitoring/lib/python2.7/site-packages/gunicorn/arbiter.py", line 459, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Hello all, 

I've installed the virtual environment and then turned the monitoring on and executed gunicorn command. It said that app modules were missing. I've copied the modules app.py and app.pyc and moved them to gunicorn folder. Then re-run the command and experienced this issues. 
My environment: 
Openstack liberty.
It is a packstack installation. controller and compute nodes are running on the same machine. 

Thanks

**Comment by renato-farias** [comment]
Can you show me your directory tree?
